Repository OpenVPN/easy-rsa, pull requests merged in 2022-04, with the labels that each got.

#521 Remove obsolete function copy_data_to_pki()
  easyrsa3/easyrsa
Labels: Full-Approval

#524 Make gen_req() Always use EASYRSA_REQ_CN as intended
  easyrsa3/easyrsa
Labels: Full-Approval, documentation, Priority, bug-fix, testing branch

#529 Remove inline file for revoke and renew
  easyrsa3/easyrsa
Labels: enhancement, Full-Approval

#526 Use x509-types 'ca' and COMMON when building a CA
  easyrsa3/easyrsa
  easyrsa3/openssl-easyrsa.cnf
Labels: Full-Approval, documentation, Priority, URGENT, bug-fix, testing branch, Major-Changes-TCT

#527 shellcheck recommendations (Ongoing)
  easyrsa3/easyrsa
Labels: Priority, initial-approval, shellcheck

#523 Separate silent-mode from batch-mode - Respect batch-mode
  ChangeLog
  easyrsa3/easyrsa
Labels: Full-Approval, documentation, Priority, bug-fix, discussion, testing branch, Major-Changes-TCT

#528 Introduce new vars_setup() regime
  easyrsa3/easyrsa
Labels: documentation, Priority, URGENT, bug-fix, discussion, Major-Changes-TCT

#534 Silence cleanup()
  easyrsa3/easyrsa
Labels: Full-Approval

#533 Detect Windows and Git-for-Windows bash
  easyrsa3/easyrsa
Labels: enhancement, Full-Approval, documentation

#535 Remove EASYRSA_EXTRA_EXTS code injection inside 'sed' script.
  easyrsa3/easyrsa
Labels: feedback-requested, Full-Approval, Priority, bug-fix

#536 easyrsa_openssl() - Minor syle changes
  easyrsa3/easyrsa
Labels: Full-Approval

#537 build_ca() - Quote temporary password file "$out_key_pass_tmp"
  easyrsa3/easyrsa
Labels: Full-Approval, documentation, shellcheck, spaces, bug-fix, Major-Changes-TCT

#541 Replace non-POSIX mktemp with POSIX mkdir and mv
  easyrsa3/easyrsa
Labels: Full-Approval, Priority

#542 Make build-ca() almost completely SSL library version independent
  easyrsa3/easyrsa
  easyrsa3/openssl-easyrsa.cnf
Labels: enhancement, Full-Approval, Priority, X509

#544 added option to set PKCS#12 alias name
  easyrsa3/easyrsa
Labels: enhancement, Full-Approval, Priority

#546 revoke(): Purge unquoted $opts + General improvements
  easyrsa3/easyrsa
Labels: Full-Approval, Priority, shellcheck, bug-fix

#547 Introduce 'revoke-renewed'
  easyrsa3/easyrsa
Labels: Full-Approval, Priority, bug-fix
