Repository OpenVPN/easy-rsa, pull requests merged in 2022-08, with the labels that each got.

#616 Introduce 'renew-req': Create new CSR for an existing private key
  ChangeLog
  easyrsa3/easyrsa
Labels: enhancement, Major-Changes-v3.1.0

#617 Restore files when 'renew' fails during 'build_full()' phase
  easyrsa3/easyrsa
Labels: BUG

#618 Ensure 'pki/renewed/<folders>' exist for 'rewind-renew'
  easyrsa3/easyrsa
Labels: BUG

#635 Allow vars file to exist in current directory (Fix make-cadir)
  easyrsa3/easyrsa
Labels: BUG-FIX, improvement

#636 gen-dh: Use temporary file
  easyrsa3/easyrsa
Labels: improvement, Applicable to v3.0.x

#637 sign--req: Prohibit COMMON as a certificate type
  easyrsa3/easyrsa
Labels: BUG-FIX, Applicable to v3.0.x

#639 show: Reorder parameter checks to guard against empty input
  easyrsa3/easyrsa
Labels: BUG-FIX

#638 verify_ca_init: Reorder names to improve error message
  easyrsa3/easyrsa
Labels: improvement, Applicable to v3.0.x

#641 Expand the possible values of $prog_dir, include full path
  easyrsa3/easyrsa
Labels: improvement, Applicable to v3.0.x

#642 vars_setup(): Always warn about unsupported characters in vars
  easyrsa3/easyrsa
Labels: improvement

#645 renew: Improve notices and input check
  easyrsa3/easyrsa
Labels: BUG-FIX, improvement

#646 Options: Check that $val is numeric when a number is expected
  easyrsa3/easyrsa
Labels: improvement, Applicable to v3.0.x

#649 Unsupported characters: Correct check and warning message
  easyrsa3/easyrsa
  easyrsa3/vars.example
Labels: improvement

#650 sign-req: Enforce X509-type files exist and are used. (#581)
  easyrsa3/easyrsa
Labels: BUG-FIX, Applicable to v3.0.x

#652 cleanup: Make "clean line" respect silent, batch and quiet modes
  easyrsa3/easyrsa
Labels: BUG-FIX, Applicable to v3.0.x

#655 Overhaul vars detection
  easyrsa3/easyrsa
Labels: enhancement, improvement, Applicable to v3.0.x, Version 3.1.x

#656 detect_host: Use SSL Library version from EasyRSA version
  easyrsa3/easyrsa
Labels: improvement, Version 3.1.x

#657 Options: Add '-s' to also enabe --silent mode.
  easyrsa3/easyrsa
Labels: enhancement, Applicable to v3.0.x, Version 3.1.x

#660 Options: Rescind deprecation notice of option --req-cn
  easyrsa3/easyrsa
Labels: documentation

#662 x509-types: Add x509-types location to usage() STATUS
  easyrsa3/easyrsa
Labels: enhancement, documentation, X509-types

#665 vars_setup: Correctly locate x509-types for usage() directory STATUS
  easyrsa3/easyrsa
Labels: BUG-FIX, Applicable to v3.0.x

#666 x509-types: Reset non-existent x509-types dir set by vars
  easyrsa3/easyrsa
Labels: BUG, Applicable to v3.0.x

#670 fixed typo
  easyrsa3/easyrsa
Labels: BUG-FIX, Applicable to v3.0.x, Version 3.1.x
