Repository OpenVPN/easy-rsa, pull requests merged in 2022-05, with the labels that each got.

#551 Display certificates in UTF8
  easyrsa3/easyrsa
Labels: initial-approval, vague, development

#550 Set notBefore/notAfter to the beginning of the year to issuing certificate (v2)
  easyrsa3/easyrsa
Labels: initial-approval, development

#562 Always respect --vars=file
  easyrsa3/easyrsa
Labels: BUG, initial-approval

#557 Introduce extensible PKI reporting tool framework
  easyrsa3/easyrsa
Labels: enhancement, Full-Approval, documentation, Major-Changes-TCT

#555 Add command for testing which certificates are eligible for renewal
  easyrsa3/easyrsa
Labels: enhancement, Full-Approval, documentation

#574 Standardise all output for warn(), notice() and message():[New]
  easyrsa3/easyrsa
Labels: Priority

#577 Expand status reports to include checking a single certificate
  ChangeLog
  easyrsa3/easyrsa
Labels: enhancement

#579 Introduce 'rewind-renew' - Recover "guineapig" renewed certificates
  ChangeLog
  easyrsa3/easyrsa
Labels: conflicts, BUG-FIX

#580 Improve revocation and renewal functions
  easyrsa3/easyrsa
Labels: improvement

#584 Correctly quote 'sed' and auto-escape ampersand
  easyrsa3/easyrsa
Labels: enhancement, Priority, OpenSSL-Config, BUG-FIX, Solution, Major-Changes-TCT
