Repository OpenVPN/easy-rsa, pull requests merged in 2022-03, with the labels that each got.

#492 Introduce support for OpenSSL version 3
  easyrsa3/easyrsa
Labels: documentation, Initial approval

#463 small typo fix
  doc/Intro-To-PKI.md
Labels: Initial approval

#495 Re-arrange "# Signing a request" to fix markdown problem
  .github/workflows/action.yml
  doc/EasyRSA-Readme.md
Labels: documentation

#496 OpenSSL Configuration: Add required white space separator
  easyrsa3/openssl-easyrsa.cnf
Labels: Full approval

#455 Simple maintenance improvements
  .travis.yml
  ChangeLog
  Licensing/gpl-2.0.txt
  README.md
  build/build-dist.sh
  distro/README
  distro/windows/EasyRSA-Start.bat
  distro/windows/README-OpenSSL.txt
  distro/windows/README-Windows.txt
  doc/EasyRSA-Advanced.md
  doc/EasyRSA-Readme.md
  doc/TODO
  easyrsa3/easyrsa
  easyrsa3/openssl-easyrsa.cnf
  easyrsa3/vars.example
  easyrsa3/x509-types/ca
  easyrsa3/x509-types/client
  easyrsa3/x509-types/code-signing
  easyrsa3/x509-types/email
  easyrsa3/x509-types/server
  easyrsa3/x509-types/serverClient
  wop_test.bat
  wop_test.sh
Labels: Full approval

#460 Add possibility to configure umask
  doc/EasyRSA-Advanced.md
  easyrsa3/easyrsa
Labels: Full approval

#426 Update EasyRSA-Readme.md
  doc/EasyRSA-Readme.md
Labels: Full approval

#500 Windows unit test: On error then exit with error
  wop_test.bat
Labels: bug, Full approval, Priority

#427 Bugfix/spaces in path
  easyrsa3/easyrsa
Labels: Priority, conflicts, Reminder, shellcheck

#505 Expand new verify_ssl_lib() to support LibreSSL version 2.x (again)
  easyrsa3/easyrsa
Labels: bug-fix

#507 Add SSL Library version 2 to easyrsa_openssl()
  easyrsa3/easyrsa
Labels: bug-fix

#510 Introduce install_data_to_pki() - Copy data-files to PKI
  easyrsa3/easyrsa
Labels: feedback-requested, Full-Approval, Priority, development, Community approval

#67 added support to specify open-ssl config file using --ssl-conf command flag
  easyrsa3/easyrsa
Labels: clarification-requested, Full-Approval, Priority, OpenSSL-Config, development

#515 Add notice to 'init-pki': 'vars' file has now moved to PKI above
  easyrsa3/easyrsa
Labels: Full-Approval

#516 copy_data_to_pki(): Immediate exit-with-error or 'shift' on success
  easyrsa3/easyrsa
Labels: Full-Approval

#307 Add authority information access example
  easyrsa3/x509-types/COMMON
Labels: Full-Approval, Priority, vague

#418 Fix renew on OpenBSD
  easyrsa3/easyrsa
Labels: Full-Approval, Priority
