Repository OpenVPN/easy-rsa, pull requests merged in 2023-09, with the labels that each got.

#1021 Forbid "default vars in the default PKI" for all commands
  ChangeLog
  easyrsa3/easyrsa
Labels: development, Major-Changes-v3.1.x, ChangeLog Item, Version 3.1.7

#1016 CI: action, checkout v4
  .github/workflows/action.yml
Labels: Version 3.1.7, Maintenance

#1023 show-expire: Calculate certificate expire seconds from Database date
  ChangeLog
  easyrsa3/easyrsa
Labels: BUG-FIX, ChangeLog Item, Version 3.1.7

#1013 Expand help to include undocumented commands
  easyrsa3/easyrsa
Labels: ChangeLog Item, improvement, Version 3.1.7

#1024 New command: make-vars - Print vars.example (here-doc) to stdout
  ChangeLog
  easyrsa3/easyrsa
Labels: ChangeLog Item, improvement, Version 3.1.7

#1020 gen-crl: preserve existing crl.pem ownership+mode
  easyrsa3/easyrsa
Labels: documentation, ChangeLog Item, Feature request, Version 3.1.7

#1025 Improve vars auto load
  easyrsa3/easyrsa
Labels: development, ChangeLog Item, Version 3.1.7
