Repository OpenVPN/easy-rsa, pull requests merged in 2024-01, with the labels that each got.

#1057 export-p12: New command option 'legacy'
  ChangeLog
  easyrsa3/easyrsa
Labels: enhancement, Version 3.2.0-beta2

#1055 `v3.2.0-beta2`
  ChangeLog
  README.md
  easyrsa3/easyrsa
Labels: BUG-FIX, Version 3.2.0-beta2

#1064 Replace use of `sed` with `heredoc` expansion
  easyrsa3/easyrsa
Labels: LibreSSL, EasyRSA-OpenSSL-Config, improvement, Version 3.2.0-Release

#1070 Restore 128bit-random certificate serial-number
  easyrsa3/easyrsa
Labels: BUG, BUG-FIX, Version 3.2.0-alpha1

#1071 LibreSSL: Add band-aid fix for missing 'x509' command option '-ext'
  easyrsa3/easyrsa
Labels: LibreSSL
